mac80211: Revert 'KERNEL_MAKEOPTS instead of KERNEL_MAKE_FLAGS'
Causes an issue when enabling NSS feature.

ERROR: modpost: "nss_virt_if_create_sync" "undefined"
ERROR: modpost: "nss_virt_if_destroy_sync"
ERROR: modpost: "nss_virt_if_register"
ERROR: modpost: "nss_virt_if_tx_buf"